# Generated by Django 5.0 on 2025-10-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoexamia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='contraseña',
        ),
    ]
