# Generated by Django 5.0 on 2025-10-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examia_backend', '0002_remove_alumno_contraseña_remove_profesor_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenalumno',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('pendiente', 'Pendiente de corrección'), ('corregido', 'Corregido')], default='activo', max_length=20),
        ),
    ]
