# Generated by Django 5.0 on 2025-10-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examia_backend', '0003_examenalumno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenalumno',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examenalumno',
            name='tiempo_utilizado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opciones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='respuestaalumno',
            name='fecha_respuesta',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='examenalumno',
            name='fecha_realizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('multiple_choice', 'Opción Múltiple'), ('desarrollo', 'Desarrollo'), ('texto', 'Texto Corto')], max_length=50),
        ),
    ]
