# Generated by Django 5.0 on 2025-10-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examia_backend', '0004_examenalumno_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaalumno',
            name='retroalimentacon',
            field=models.TextField(blank=True),
        ),
    ]
