# Generated by Django 5.0 on 2025-10-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examia_backend', '0005_respuestaalumno_retroalimentacon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestaalumno',
            old_name='retroalimentacon',
            new_name='retroalimentacion',
        ),
        migrations.AlterField(
            model_name='examenalumno',
            name='fecha_realizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
