# Generated by Django 5.0 on 2025-10-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examia_backend', '0006_rename_retroalimentacon_respuestaalumno_retroalimentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo_acceso',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
